-- 산술연산자

SELECT ename, sal, sal * 1.1
FROM T_EMP ;

SELECT ENAME , SAL , COMM , SAL +COMM  --null 값과의 산술 결과는 모두 null이다
FROM T_EMP ;

--WHERE 조건절
SELECT * FROM T_EMP WHERE job = 'SALESMAN';

SELECT ename, sal, deptno
FROM T_EMP WHERE DEPTNO = 10;

SELECT  ename, sal
FROM T_EMP WHERE sal > 2000;

SELECT  empno, ename, sal
FROM T_EMP WHERE ENAME = 'SCOTT';

SELECT * FROM T_STUDENT ;

SELECT name, grade
FROM T_STUDENT WHERE grade IN (2,3);
SELECT name, grade
FROM T_STUDENT WHERE grade=2 OR grade = 3;
SELECT name, grade
FROM T_STUDENT WHERE grade > 1 AND GRADE < 4;
SELECT name, grade
FROM T_STUDENT WHERE grade NOT IN (1,4);
SELECT name, grade
FROM T_STUDENT WHERE grade BETWEEN 2 AND 3;

SELECT NAME , PAY , POSITION 
FROM T_PROFESSOR WHERE PAY > 300 AND POSITION = '정교수';

SELECT * FROM T_PROFESSOR ;

SELECT NAME , POSITION 
FROM T_PROFESSOR WHERE BONUS IS NULL ;

SELECT NAME 
FROM T_PROFESSOR WHERE NAME  LIKE '김%';

SELECT ENAME 
FROM T_EMP WHERE ENAME LIKE '%NE%';

SELECT ENAME 
FROM T_EMP WHERE ENAME LIKE '_A%';

-- ORDER BY
SELECT ENAME 
FROM T_EMP WHERE ENAME LIKE '%L%'
ORDER BY ENAME DESC ;

SELECT ename, job, sal FROM T_EMP 
ORDER BY JOB DESC, sal ASC;

SELECT NAME , GRADE , HEIGHT FROM T_STUDENT
ORDER BY GRADE ASC, HEIGHT DESC ;








