-- DB03
--1번
SELECT * FROM T_STUDENT WHERE HEIGHT >= 180;

--2번
SELECT NAME , WEIGHT FROM T_STUDENT WHERE WEIGHT BETWEEN 60 AND 80;

--3번
SELECT * FROM T_STUDENT WHERE DEPTNO1 IN (101,201);  

--4번
SELECT * FROM T_STUDENT WHERE NAME LIKE '김%';

--5번
SELECT NAME , GRADE , HEIGHT FROM T_STUDENT WHERE GRADE = 4 AND HEIGHT >= 170;

--6번
SELECT NAME , HEIGHT , GRADE , WEIGHT FROM T_STUDENT
WHERE GRADE = 1 OR WEIGHT >= 80;

--7번
SELECT NAME , GRADE , HEIGHT , WEIGHT FROM T_STUDENT 
WHERE GRADE = 2 AND HEIGHT > 180 AND  WEIGHT > 70;

--8번
SELECT NAME , GRADE , WEIGHT , HEIGHT FROM T_STUDENT 
WHERE GRADE = 2 AND (HEIGHT > 180 OR WEIGHT  > 70);

--9번
SELECT ENAME , HIREDATE FROM T_EMP
WHERE HIREDATE < '1992-01-01';

--10번
SELECT NAME , BIRTHDAY , HEIGHT , WEIGHT FROM T_STUDENT
WHERE GRADE = 1
ORDER BY BIRTHDAY ASC ;

--11번
SELECT NAME AS 이름, HEIGHT AS 키 FROM T_STUDENT WHERE GRADE = 1
ORDER BY NAME ASC;

--12번
SELECT NAME , BIRTHDAY FROM T_EMP2 
WHERE BIRTHDAY BETWEEN '1980/01/01' AND '1989/12/31';








