--#7201
SELECT GRADE "학년", NAME "이름", HEIGHT "키"
FROM T_STUDENT 
WHERE (GRADE , HEIGHT) IN (SELECT grade, MAX(HEIGHT ) FROM T_STUDENT GROUP BY GRADE)
ORDER BY "학년" ASC ;

--#7202
SELECT p.PROFNO "교수번호", p.NAME "교수명", p.HIREDATE "입사일", d.DNAME "학과명"
FROM T_PROFESSOR p , T_DEPARTMENT d
WHERE p.DEPTNO = d.DEPTNO AND (p.DEPTNO, p.HIREDATE) IN 
	(SELECT DEPTNO , MIN(HIREDATE) FROM T_PROFESSOR GROUP BY DEPTNO)
ORDER BY "학과명" ASC;

--#7203
SELECT NAME "사원명", POST "직급", PAY "연봉"
FROM T_EMP2 
WHERE (POST, PAY ) IN (SELECT POST , MAX(PAY ) FROM T_EMP2 GROUP BY POST )
ORDER BY "연봉" ASC;

--#7204
SELECT D.DNAME "부서명", E.NAME "직원명", E.PAY "연봉"
FROM T_EMP2 E , T_DEPT2 D
WHERE E.DEPTNO = D.DCODE AND PAY <ALL  
	(SELECT AVG(PAY) FROM T_EMP2 GROUP BY DEPTNO)
ORDER BY "연봉";

--#7205
SELECT A.NAME "사원이름", NVL(A.POST, ' ') "직급", A.PAY "급여"
FROM T_EMP2 A
WHERE A.PAY >= (SELECT AVG(B.PAY) FROM T_EMP2 B WHERE NVL(A.POST, ' ') = NVL(B.POST, ' '));

--#7206 (스칼라 서브쿼리)
SELECT NAME "사원이름", (SELECT D.DNAME FROM T_DEPT2 D WHERE E.DEPTNO = D.DCODE ) "부서이름"
FROM T_EMP2 E;




