--INITCAP() 함수

--#4101
SELECT INITCAP('pretty girl') FROM DUAL;

--#4102
SELECT INITCAP(ID) FROM T_STUDENT WHERE DEPTNO1 = 201;

-- LOWER , UPPER
--#4103
SELECT NAME, ID, LOWER(ID) "소문자", UPPER(ID) "대문자" 
FROM T_STUDENT 
WHERE DEPTNO1 = 201;

--LENGTH, LENGTHB
--#4104
SELECT NAME , ID , LENGTH(ID ) FROM T_STUDENT WHERE LENGTH(ID) >= 9;

--#4105
SELECT NAME , LENGTH (NAME), LENGTHB(NAME) FROM T_STUDENT WHERE DEPTNO1 = 201;

--CONCAT
--#4106
SELECT CONCAT(NAME , POSITION ) AS 교수님명단 FROM T_PROFESSOR WHERE DEPTNO = 101;

--SUBSTR
SELECT SUBSTR('ABCDE',-3, 2) FROM DUAL;
SELECT SUBSTR('ABCDE', 20, 3) FROM DUAL ; -- NULL 나옴 에러 아님!
--#4107
SELECT NAME , SUBSTR(JUMIN, 1,6) AS 생년월일 FROM T_STUDENT WHERE DEPTNO1 = 101;
--#4108
SELECT NAME , SUBSTR(JUMIN ,1,6) FROM T_STUDENT WHERE SUBSTR(JUMIN ,3,2) ='08';
--#4109
SELECT NAME , JUMIN FROM T_STUDENT WHERE GRADE = 4 AND SUBSTR(JUMIN, 7,1) = '2';

-- INSTR() 함수
SELECT INSTR('A*B*C*','*', 1 , 1) FROM DUAL ; --2
SELECT INSTR('A*B*C*','*', 1 , 2) FROM DUAL ; --4
SELECT INSTR('A*B*C*','*', 3 , 2) FROM DUAL ; --6
SELECT INSTR('A*B*C*','*', -4 , 1) FROM DUAL ; --2 , 음수 인덱스의 경우 검색도 음의 방향으로 진행
SELECT INSTR('A*B*C*','*', -4 , 2) FROM DUAL ; --0 , 없으면 0 리턴
SELECT INSTR('A*B*C*','*', -2 , 2) FROM DUAL ; --2 
--#4110
SELECT NAME , TEL , INSTR(TEL, ')') AS LOCAL FROM T_STUDENT WHERE DEPTNO1 = 101;
--#4111
SELECT NAME , TEL , SUBSTR(TEL,1,INSTR(TEL, ')')-1) AS 지역번호 FROM T_STUDENT WHERE DEPTNO1 = 101;

-- LTRIM, RTRIM , TRIM
SELECT LTRIM('슈퍼슈퍼슈가맨', '슈퍼') LTRIM, 
	   LTRIM('    슈퍼슈가맨') LTRIM2,
	   RTRIM('슈퍼슈가맨      ') RTRIM,
	   TRIM('     슈퍼맨       ') TRIM, --좌우공백 다 제거
	   LTRIM('######$@#$%문자만', '#@$%') AS 문자열
FROM DUAL;

--#4117
SELECT * FROM T_DEPT2 ;
SELECT DNAME , RTRIM(DNAME, '부') AS RTRIM예제 FROM T_DEPT2 ;

--REPLACE 함수
SELECT REPLACE ('슈퍼맨 슈퍼걸', '슈퍼' , '파워') FROM DUAL ;
SELECT REPLACE ('아버지가  방에 들어간다', ' ', '') FROM DUAL ;

--#4118
SELECT REPLACE(NAME,SUBSTR(NAME,1,1) ,'#') FROM T_STUDENT WHERE DEPTNO1 = 102;
--#4119
SELECT REPLACE (NAME,SUBSTR(NAME,2,1), '#')FROM T_STUDENT WHERE DEPTNO1 = 101;
--#4120
SELECT NAME, REPLACE (JUMIN ,SUBSTR(JUMIN ,7), '*******')AS 주민번호 FROM T_STUDENT WHERE DEPTNO1 = 101;
--#4121
SELECT NAME, TEL, REPLACE (TEL, SUBSTR(TEL ,INSTR(TEL, ')')+1,3), '###') AS 전화번호 FROM T_STUDENT WHERE DEPTNO1 = 102;






